"""Render an AuditReport as markdown.

The output mirrors Carlos's manual audit format (capability map →
findings → score) so anyone who's seen one of those manual reports
recognizes the structure immediately.
"""

from __future__ import annotations

from datetime import datetime, timezone

from audit.findings import AuditReport, Finding


def render_markdown(r: AuditReport, tool_version: str = "0.1.0") -> str:
    s = r.scan
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines: list[str] = []

    # Header
    pkg_name = _guess_package_name(r)
    lines.append(f"# Security Audit: {pkg_name}")
    lines.append("")
    lines.append(f"- **Generated:** {ts}")
    lines.append(f"- **Tool:** mcp-audit v{tool_version}")
    lines.append(f"- **Source:** `{s.target_path}`")
    lines.append(f"- **Files scanned:** {s.files_scanned} ({s.lines_scanned:,} lines)")
    lines.append("")

    # Score banner
    lines.append(f"## Score: {r.score}/10 — {_score_label(r.score)}")
    lines.append("")
    if r.score_explanation:
        for e in r.score_explanation:
            lines.append(f"- {e}")
        lines.append("")

    # Capability map
    lines.append("## Capabilities (auto-detected)")
    lines.append("")
    lines.append("### What this package CAN do")
    if r.capabilities_yes:
        for c in r.capabilities_yes:
            lines.append(f"- ✅ {c}")
    else:
        lines.append("- (nothing detected)")
    lines.append("")

    lines.append("### What this package does NOT do")
    if r.capabilities_no:
        for c in r.capabilities_no:
            lines.append(f"- ❌ {c}")
    else:
        lines.append("- (could not establish negatives — review manually)")
    lines.append("")

    # Dependencies
    lines.append("## Dependencies")
    lines.append("")
    if s.dependencies:
        lines.append(f"From `{s.dep_source}`:")
        lines.append("")
        for d in s.dependencies:
            lines.append(f"- `{d}`")
    else:
        lines.append(f"No declared dependencies (source: {s.dep_source}).")
    lines.append("")

    # Findings
    lines.append("## Findings")
    lines.append("")
    if not r.findings:
        lines.append("**No issues detected.** The package is well-scoped to a single read-only outbound HTTP integration with no shell, filesystem, or inbound network surface.")
        lines.append("")
    else:
        for sev_label in ("high", "medium", "low", "info"):
            bucket = [f for f in r.findings if f.severity == sev_label]
            if not bucket:
                continue
            lines.append(f"### {sev_label.capitalize()} ({len(bucket)})")
            lines.append("")
            for f in bucket:
                lines.append(f"#### {f.title}")
                lines.append("")
                lines.append(f"- **Dimension:** {f.dimension}")
                lines.append(f"- **Severity:** {f.severity}")
                lines.append(f"- **Score impact:** −{f.deduction}")
                if f.detail:
                    lines.append(f"- **Detail:** {f.detail}")
                lines.append("")

    # Methodology footer
    lines.append("## Scoring methodology")
    lines.append("")
    lines.append(
        "Score starts at 10. Each finding deducts a fixed amount based on severity:"
    )
    lines.append("")
    lines.append("- **High** (−2 to −3 each): subprocess with shell=True, dynamic exec, TLS verification disabled, suspicious env var reads")
    lines.append("- **Medium** (−1 to −2 each): subprocess without shell, filesystem writes, inbound network listeners, dynamic URL destinations, broad-credential env reads")
    lines.append("- **Low** (0 to −1 each): URL constructed via f-string/concat, multiple outbound hosts, loose version pins")
    lines.append("- **Info** (no deduction): observed behavior worth noting (e.g., reads from filesystem)")
    lines.append("")
    lines.append("Recommendation thresholds:")
    lines.append("")
    lines.append("- **8–10**: Low-risk for friend distribution. Audit confirms a narrow capability surface.")
    lines.append("- **5–7**: Medium-risk. Document the flagged behaviors; install with awareness.")
    lines.append("- **0–4**: High-risk. Do not install without manual review of the flagged sites.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [mcp-audit](https://github.com/bradylandry/mcp-audit) — static-analysis security audit for Python MCP packages. Pure stdlib, no LLM, no network, fully reproducible. Same input → same output.*")

    return "\n".join(lines) + "\n"


# ── Helpers ─────────────────────────────────────────────────────────────────

def _score_label(score: int) -> str:
    if score >= 8:
        return "low risk"
    if score >= 5:
        return "medium risk — review findings"
    return "high risk — manual review required"


def _guess_package_name(r: AuditReport) -> str:
    """Best-effort package name from the target path."""
    from pathlib import Path
    p = Path(r.scan.target_path)
    return p.name or "package"
